sudo: required
language: python
cache: pip

install:
  - pip install awscli
  - pip install flake8

before_script:
  - docker build -t finanzen-entgelt -f Dockerfile.dev \
      --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} \
      --build-arg ECR_REGISTRY=${ECR_REGISTRY} \
      --build-arg ECR_REPOSITORY=${ECR_REPOSITORY} \
      .

script:
  - flake8
  - docker run finanzen-entgelt pytest

deploy:
  skip_cleanup: true
  provider: script
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  script: ./build_push_image.sh
  on:
    all_branches: true
