sudo: required
services:
  - docker

before_install:
  - docker build -t finanzen-entgelt -f Dockerfile.dev --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} .
 
script:
  - docker run finanzen-entgelt pytest
