sudo: required
language: python
cache: pip

install:
  - pip install awscli
  - pip install flake8

before_script:
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - docker login -u AWS -p $(aws --region us-east-2 ecr get-login-password) ${ECR_REGISTRY}
  - docker build -t finanzen-entgelt-dev -f Dockerfile.dev --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} --build-arg ECR_REGISTRY=${ECR_REGISTRY} --build-arg ECR_REPOSITORY=${ECR_REPOSITORY} .

script:
  - flake8
  - docker run finanzen-entgelt-dev pytest

deploy:
  skip_cleanup: true
  provider: script
  script: ./build_push_image.sh
  on:
    all_branches: true
